== table
Status: *Stable*

The table panel contains a sortable, pagable view of documents that. It can be arranged into
defined columns and offers several interactions, such as performing adhoc terms aggregations.

// src/app/panels/table/module.js:5

=== Parameters

size:: The number of hits to show per page
// src/app/panels/table/module.js:60

pages:: The number of pages available
// src/app/panels/table/module.js:66

offset:: The current page
// src/app/panels/table/module.js:70

sort:: An array describing the sort order of the table. For example [`@timestamp',`desc']
// src/app/panels/table/module.js:74

overflow:: The css overflow property. `min-height' (expand) or `auto' (scroll)
// src/app/panels/table/module.js:78

fields:: the fields used a columns of the table, in an array.
// src/app/panels/table/module.js:82

highlight:: The fields on which to highlight, in an array
// src/app/panels/table/module.js:86

sortable:: Set sortable to false to disable sorting
// src/app/panels/table/module.js:90

header:: Set to false to hide the table column names
// src/app/panels/table/module.js:94

paging:: Set to false to hide the paging controls of the table
// src/app/panels/table/module.js:98

field_list:: Set to false to hide the list of fields. The user will be able to expand it,
but it will be hidden by default
// src/app/panels/table/module.js:102

all_fields:: Set to true to show all fields in the mapping, not just the current fields in
the table.
// src/app/panels/table/module.js:107

trimFactor:: The trim factor is the length at which to truncate fields takinging into
consideration the number of columns in the table. For example, a trimFactor of 100, with 5
columns in the table, would trim each column at 20 character. The entirety of the field is
still available in the expanded view of the event.
// src/app/panels/table/module.js:112

localTime:: Set to true to adjust the timeField to the browser's local time
// src/app/panels/table/module.js:119

timeField:: If localTime is set to true, this field will be adjusted to the browsers local time
// src/app/panels/table/module.js:123

spyable:: Set to false to disable the inspect icon
// src/app/panels/table/module.js:127

==== Queries
queries object:: This object describes the queries to use on this panel.
queries.mode::: Of the queries available, which to use. Options: +all, pinned, unpinned, selected+
queries.ids::: In +selected+ mode, which query ids are selected.
// src/app/panels/table/module.js:131

